# Copa do Mundo 2022: Seleção dos Dados

## Adicionando Datasets

In [161]:
# Importando as bibliotecas que serão usadas para as análises
import pandas as pd
import numpy as np

In [162]:
# Datasets de estatísticas e dados mistos sobre todos os jogadores
df_stats = pd.read_csv('data\player_stats.csv')
df_playtime = pd.read_csv('data\player_playingtime.csv')
df_passing = pd.read_csv('data\player_passing.csv')
df_possesion = pd.read_csv('data\player_possession.csv')
df_misc = pd.read_csv('data\player_misc.csv')
df_shooting = pd.read_csv('data\player_shooting.csv')
df_gca = pd.read_csv('data\player_gca.csv')
df_defense = pd.read_csv('data\player_defense.csv')

# Datasets com estatísticas acerca dos goleiros
df_keepers = pd.read_csv('data\player_keepers.csv')
df_keepers_adv = pd.read_csv('data\player_keepersadv.csv')

## Separação de colunas por posição e definição de KPI´s

- Selecionando as colunas necessárias para as análises de cada posição

**df_geral**: name, age, position, touches,  dribbles , dribbles_completed, passes_received, passes_completed, minutes_per_game, cards_yellow, cards_red, fouls, fouled, Goals, xg_assist , assists

**df_atacante**: xg, shots, shots_on_target, shots_on_target_pct, goals_per_shot, goals_per_shot_on_target, crosses, gca

**df_meioCampo**: crosses, gca, passes_completed_short, passes_short, passes_pct_short, passes_completed_medium, passes_medium, passes_pct_medium, passes_completed_long, passes_long, passes_pct_long, progressive_passes,tackles, tackles_won, blocked_passes, interceptions

**df_zagueiro**: tackles, tackles_won, blocked_passes, interceptions, errors, aerials_won_pct, ball_recoveries, pens_conceded, own_goals

**df_goleiro**: gk_goals_against, gk_shots_on_target_against, gk_save_pct, gk_clean_sheets, gk_pens_att, gk_pens_allowed, gk_pens_saved, gk_pens_save_pct, gk_passes, gk_passes_completed_launched, gk_passes_completed_launched, gk_passes_length_avg, gk_goal_kick_length_avg, gk_crosses_stopped

### df_geral

In [163]:
# Criando o df_geral com base numa cópia do df_stats:
df_geral = df_stats[[
    'player', 'position', 'team', 'age', 
    'assists' , 'goals', 'cards_yellow', 'cards_red'
    ]].copy()

# Pegando outras colunas de outros datasets para compor o df_geral:
df_geral['minutes_per_game'] = df_playtime['minutes_per_game']

df_geral[[
    'touches', 'dribbles', 'dribbles_completed', 'passes_received']] = possesion[[
    'touches', 'dribbles', 'dribbles_completed', 'passes_received']]

df_geral['passes_completed'] = df_passing['passes_completed']
df_geral[['fouls', 'fouled']] = df_misc[['fouls', 'fouled']]

In [164]:
df_geral.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,dribbles,dribbles_completed,passes_received,passes_completed,fouls,fouled
0,Aaron Mooy,MF,Australia,32-094,0,0,1,0,NaN,255.0,3.0,2.0,152.0,170.0,4,1
1,Aaron Ramsey,MF,Wales,31-357,0,0,1,0,90.0,147.0,8.0,2.0,98.0,88.0,3,3
2,Abdelhamid Sabiri,MF,Morocco,26-020,1,0,1,0,NaN,86.0,3.0,0.0,54.0,45.0,2,3

- Como o df_geral sera usado como baseline para a criação dos outros datasets, é necessário termos certeza de que suas colunas e datatypes sejam válidos.

In [165]:
df_geral.dtypes

player                 object
position               object
team                   object
age                    object
assists                 int64
goals                   int64
cards_yellow            int64
cards_red               int64
minutes_per_game      float64
touches               float64
dribbles              float64
dribbles_completed    float64
passes_received       float64
passes_completed      float64
fouls                   int64
fouled                  int64
dtype: object

Com essa visão, podemos tirar algumas conclusões:

- A coluna "age" está num formato não adequado, mostrando quantos anos e dias o atleta tem na mesma coluna num formato de string, o que impossibilita qualuqer análise posterior sobre as idades dos jogadores. Para solucionar isso, modificaremos a coluna age para mostrar apenas o ano como idade.

- As colunas que estão no formato float64 não tem justificativa para isso, sendo recomendado a trasnformação das mesmas para int64, já que nenhuma possui valor decimal.

Com isso, vamos as transformações:

In [166]:
# Ajeitando a coluna 'age' para mostrar apenas o ano
df_geral['age'] = df_geral['age'].apply(lambda x: str(x)[0:2])

# Transformando dtypes para int:
df_geral['age'] = df_geral['age'].astype(int)

In [167]:
df_geral.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,dribbles,dribbles_completed,passes_received,passes_completed,fouls,fouled
0,Aaron Mooy,MF,Australia,32,0,0,1,0,NaN,255.0,3.0,2.0,152.0,170.0,4,1
1,Aaron Ramsey,MF,Wales,31,0,0,1,0,90.0,147.0,8.0,2.0,98.0,88.0,3,3
2,Abdelhamid Sabiri,MF,Morocco,26,1,0,1,0,NaN,86.0,3.0,0.0,54.0,45.0,2,3

In [168]:
# Transformando colunas que possuem float para int:
df_geral['minutes_per_game'] = df_geral['minutes_per_game'].astype('Int64')
df_geral['touches'] = df_geral['touches'].astype('Int64')
df_geral['dribbles'] = df_geral['dribbles'].astype('Int64')
df_geral['dribbles_completed'] = df_geral['dribbles_completed'].astype('Int64')  
df_geral['passes_received'] = df_geral['passes_received'].astype('Int64')  
df_geral['passes_completed'] = df_geral['passes_completed'].astype('Int64')

In [169]:
df_geral.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,dribbles,dribbles_completed,passes_received,passes_completed,fouls,fouled
0,Aaron Mooy,MF,Australia,32,0,0,1,0,<NA>,255,3,2,152,170,4,1
1,Aaron Ramsey,MF,Wales,31,0,0,1,0,90,147,8,2,98,88,3,3
2,Abdelhamid Sabiri,MF,Morocco,26,1,0,1,0,<NA>,86,3,0,54,45,2,3

### df_atacante

In [170]:
# Criando o df_atacante baseado no df_geral com uma cópia dos dados da posição FW (atacante):
df_atacante = df_geral.query('position == "FW"').copy()

# Adicionando outras colunas relevantes para a análise dos atacantes:
df_atacante[[
    'xg', 'shots','shots_on_target', 'shots_on_target_pct', 'goals_per_shot', 'goals_per_shot_on_target']] = shooting[[
    'xg', 'shots','shots_on_target', 'shots_on_target_pct', 'goals_per_shot', 'goals_per_shot_on_target']]
    
df_atacante['gca'] = df_gca['gca']
df_atacante['crosses'] = df_misc['crosses']

In [171]:
df_atacante.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,...,fouls,fouled,xg,shots,shots_on_target,shots_on_target_pct,goals_per_shot,goals_per_shot_on_target,gca,crosses
4,Abderrazak Hamdallah,FW,Morocco,32,0,0,0,0,36,28,...,3,2,0.4,2,1,50.0,0.0,0.0,0.0,0
5,Abdessamad Ezzalzouli,FW,Morocco,21,0,0,0,0,90,40,...,4,0,0.1,1,0,0.0,0.0,NaN,0.0,1
7,Abdul Fatawu Issahaku,FW,Ghana,18,0,0,0,0,31,2,...,0,0,0.0,0,0,NaN,NaN,NaN,0.0,0

### df_meioCampo

In [172]:
# Criando o df_meioCampo baseado no df_geral com uma cópia dos dados da posição MF (meio-campista):
df_meioCampo = df_geral.query('position == "MF"').copy()

# Adicionando outras colunas relevantes para a análise dos meio-campistas:
df_meioCampo[[
    'passes_completed_short',
    'passes_short', 
    'passes_pct_short', 
    'passes_completed_medium', 
    'passes_medium', 
    'passes_pct_medium', 
    'passes_completed_long', 
    'passes_long', 
    'passes_pct_long', 
    'progressive_passes' ]] = df_passing[[
    'passes_completed_short', 
    'passes_short', 
    'passes_pct_short', 
    'passes_completed_medium', 
    'passes_medium', 
    'passes_pct_medium', 
    'passes_completed_long', 
    'passes_long', 
    'passes_pct_long', 
    'progressive_passes' ]]

df_meioCampo[[
    'tackles', 'tackles_won', 'blocked_passes', 'interceptions']] = df_defense[[
    'tackles', 'tackles_won', 'blocked_passes', 'interceptions']]

df_meioCampo['xg_assist'] = df_stats['xg_assist']
df_meioCampo['crosses'] = df_misc['crosses']
df_meioCampo['gca'] = df_gca['gca']

In [173]:
df_meioCampo.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,...,passes_long,passes_pct_long,progressive_passes,tackles,tackles_won,blocked_passes,interceptions,xg_assist,crosses,gca
0,Aaron Mooy,MF,Australia,32,0,0,1,0,<NA>,255,...,31.0,58.1,14.0,9.0,6,2.0,3,0.1,10,0.0
1,Aaron Ramsey,MF,Wales,31,0,0,1,0,90,147,...,23.0,78.3,5.0,2.0,0,3.0,0,0.0,5,0.0
2,Abdelhamid Sabiri,MF,Morocco,26,1,0,1,0,<NA>,86,...,10.0,70.0,0.0,3.0,1,2.0,5,0.9,1,1.0

### df_zagueiro

In [174]:
# Criando o df_zagueiro baseado no df_geral com uma cópia dos dados da posição DF (zagueiro):
df_zagueiro = df_geral.query('position == "DF"').copy()

# Adicionando outras colunas relevantes para a análise dos zagueiros:
df_zagueiro[[
    'tackles', 'tackles_won', 'blocked_passes', 'interceptions', 'errors']] = defense[[
    'tackles', 'tackles_won', 'blocked_passes', 'interceptions', 'errors']]

df_zagueiro[[
    'aerials_won_pct', 'ball_recoveries', 'pens_conceded', 'own_goals']] = misc[[
    'aerials_won_pct', 'ball_recoveries', 'pens_conceded', 'own_goals']]

In [175]:
df_zagueiro.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,...,fouled,tackles,tackles_won,blocked_passes,interceptions,errors,aerials_won_pct,ball_recoveries,pens_conceded,own_goals
3,Abdelkarim Hassan,DF,Qatar,29,0,0,0,0,89,193,...,4,7.0,3,2.0,1,0.0,75.0,11.0,0.0,0
6,Abdou Diallo,DF,Senegal,26,0,0,0,0,17,210,...,0,2.0,2,0.0,1,0.0,53.8,17.0,0.0,0
9,Abdulelah Al-Amri,DF,Saudi Arabia,25,0,0,2,0,1,129,...,3,1.0,0,1.0,4,0.0,71.4,15.0,0.0,0

### df_goleiro

In [176]:
# Criando o df_goleiro baseado no df_geral com uma cópia dos dados da posição GK (goleiro):
df_goleiro = df_geral.query('position == "GK"').copy()

# Adicionando outras colunas relevantes para a análise dos goleiros:
df_goleiro[[
    'gk_goals_against', 
    'gk_shots_on_target_against', 
    'gk_save_pct', 
    'gk_clean_sheets', 
    'gk_pens_att', 
    'gk_pens_allowed', 
    'gk_pens_saved', 
    'gk_pens_save_pct']] = df_keepers[[
    'gk_goals_against', 
    'gk_shots_on_target_against', 
    'gk_save_pct', 
    'gk_clean_sheets', 
    'gk_pens_att', 
    'gk_pens_allowed', 
    'gk_pens_saved', 
    'gk_pens_save_pct']]

df_goleiro[[
    'gk_passes', 
    'gk_passes_completed_launched',
    'gk_passes_length_avg', 
    'gk_goal_kick_length_avg', 
    'gk_crosses_stopped']] = df_keepers_adv[[
    'gk_passes', 
    'gk_passes_completed_launched', 
    'gk_passes_length_avg', 
    'gk_goal_kick_length_avg', 
    'gk_crosses_stopped']]

In [177]:
df_goleiro.head(3)

,player,position,team,age,assists,goals,cards_yellow,cards_red,minutes_per_game,touches,...,gk_clean_sheets,gk_pens_att,gk_pens_allowed,gk_pens_saved,gk_pens_save_pct,gk_passes,gk_passes_completed_launched,gk_passes_length_avg,gk_goal_kick_length_avg,gk_crosses_stopped
20,Aimen Dahmen,GK,Tunisia,25,0,0,0,0,81,82,...,1.0,1.0,1.0,0.0,0.0,99.0,11.0,31.5,43.3,3.0
40,Alireza Beiranvand,GK,IR Iran,30,0,0,0,0,63,34,...,3.0,0.0,0.0,0.0,NaN,151.0,32.0,31.3,46.6,5.0
42,Alisson,GK,Brazil,30,0,0,0,0,72,101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN